package json_logic

import java.nio.charset.StandardCharsets

import cats.effect.IO
import cats.syntax.all._

import io.constellationnetwork.metagraph_sdk.crypto.mpt.MerklePatriciaTrie
import io.constellationnetwork.metagraph_sdk.crypto.mpt.api.{
  MerklePatriciaBatchInclusionProver,
  MerklePatriciaPrefixProver,
  MerklePatriciaProver
}
import io.constellationnetwork.metagraph_sdk.crypto.smt.impl.InMemorySparseMerkleTree
import io.constellationnetwork.metagraph_sdk.crypto.smt.{SparseMerkleProof, SparseMerkleRoot}
import io.constellationnetwork.metagraph_sdk.json_logic.core.JsonLogicOp._
import io.constellationnetwork.metagraph_sdk.json_logic.core._
import io.constellationnetwork.metagraph_sdk.json_logic.runtime.JsonLogicEvaluator
import io.constellationnetwork.security.hex.Hex

import io.circe.Json
import io.circe.syntax.EncoderOps
import weaver.SimpleIOSuite

/**
 * End-to-end tests for the WAVE 3 JLVM auth-DB opcodes: `smt_verify` (Sparse Merkle Tree
 * inclusion/absence), `mpt_verify` (Merkle Patricia Trie inclusion) and `mpt_prefix_verify` (MPT
 * authenticated, COMPLETE prefix proof).
 *
 * Each opcode is exercised end-to-end through the evaluator with real trees and real proofs
 * (generated by the native provers), with positive and negative cases, plus a worked allowlist /
 * revocation gate combining `smt_verify` with an `if`.
 *
 * Proofs and values are JSON (unlike the hex-only wave-1/2 crypto ops): a proof is generated in `IO`,
 * encoded to circe `Json` via its `Encoder`, then bridged into a JSON Logic value to build the opcode
 * expression -- exactly the JSON-proof path the opcode decodes on the way in.
 */
object AuthDbOpsWave3Suite extends SimpleIOSuite {

  // ---- bridges --------------------------------------------------------------------------------------------------------------------------

  /** circe Json -> JSON Logic value (the opcode's inbound bridge; uses the value type's own Decoder). */
  private def jsonToJlv(json: Json): JsonLogicValue =
    json.as[JsonLogicValue].fold(e => throw new RuntimeException(s"bad bridge: $e"), identity)

  /** Build an opcode expression with already-evaluated constant args. */
  private def opExpr(op: JsonLogicOp, args: JsonLogicValue*): JsonLogicExpression =
    ApplyExpression(op, args.toList.map(ConstExpression(_)))

  private def evalExpr(expr: JsonLogicExpression): IO[Either[JsonLogicException, JsonLogicValue]] =
    JsonLogicEvaluator.tailRecursive[IO].evaluate(expr, MapValue.empty, None)

  /** The JLVM hex convention: `0x`-prefixed lowercase. The primitives use raw (no `0x`) tessellation hex. */
  private def hex0x(raw: String): String = "0x" + raw.toLowerCase

  /** A JSON value stored as its UTF-8 JSON bytes, so the SMT round-trips it back to a clean value. */
  private def jsonBytes(json: Json): Array[Byte] =
    json.noSpaces.getBytes(StandardCharsets.UTF_8)

  // ===========================================================================
  // smt_verify -- inclusion + absence
  // ===========================================================================

  // A small SMT keyed by 32-byte hex keys, with JSON-encoded string values.
  private val smtKeyA: Hex = Hex("aa" * 32)
  private val smtKeyB: Hex = Hex("bb" * 32)
  private val smtKeyAbsent: Hex = Hex("cc" * 32)
  private val smtValA: Json = Json.fromString("alice")
  private val smtValB: Json = Json.fromString("bob")

  private val smtEntries: Map[Hex, Array[Byte]] =
    Map(smtKeyA -> jsonBytes(smtValA), smtKeyB -> jsonBytes(smtValB))

  private def buildSmt: IO[(SparseMerkleRoot, SparseMerkleProof, SparseMerkleProof)] =
    for {
      tree   <- InMemorySparseMerkleTree.make[IO](smtEntries)
      root   <- tree.root
      prover <- tree.prover
      inclE  <- prover.prove(smtKeyA)
      incl   <- IO.fromEither(inclE.leftMap(e => new RuntimeException(e.toString)))
      absE   <- prover.prove(smtKeyAbsent)
      abs    <- IO.fromEither(absE.leftMap(e => new RuntimeException(e.toString)))
    } yield (root, incl, abs)

  test("smt_verify: inclusion proof yields valid:true, included:true, the key and the value") {
    buildSmt.flatMap {
      case (root, incl, _) =>
        val expr = opExpr(SmtVerifyOp, StrValue(hex0x(root.value.value)), jsonToJlv(incl.asJson))
        evalExpr(expr).map { r =>
          expect(
            r == Right(
              MapValue(
                Map(
                  "valid"    -> BoolValue(true),
                  "included" -> BoolValue(true),
                  "key"      -> StrValue(hex0x(smtKeyA.value)),
                  "value"    -> StrValue("alice")
                )
              )
            )
          )
        }
    }
  }

  test("smt_verify: absence proof yields valid:true, included:false, null value") {
    buildSmt.flatMap {
      case (root, _, abs) =>
        val expr = opExpr(SmtVerifyOp, StrValue(hex0x(root.value.value)), jsonToJlv(abs.asJson))
        evalExpr(expr).map { r =>
          expect(
            r == Right(
              MapValue(
                Map(
                  "valid"    -> BoolValue(true),
                  "included" -> BoolValue(false),
                  "key"      -> StrValue(hex0x(smtKeyAbsent.value)),
                  "value"    -> NullValue
                )
              )
            )
          )
        }
    }
  }

  test("smt_verify: a tampered root makes the proof not verify (valid:false)") {
    buildSmt.flatMap {
      case (_, incl, _) =>
        val badRoot = hex0x("00" * 32)
        val expr = opExpr(SmtVerifyOp, StrValue(badRoot), jsonToJlv(incl.asJson))
        evalExpr(expr).map {
          case Right(MapValue(m)) => expect(m.get("valid").contains(BoolValue(false)))
          case other              => failure(s"expected a valid:false result map, got $other")
        }
    }
  }

  test("smt_verify: a corrupted (tampered-value) inclusion proof does not verify (valid:false)") {
    buildSmt.flatMap {
      case (root, incl, _) =>
        // Tamper the proof's value bytes WITHOUT touching valueDigest -> ValueBindingFailed -> valid:false.
        val corrupted = incl match {
          case i: SparseMerkleProof.Inclusion => i.copy(value = Hex.fromBytes(jsonBytes(Json.fromString("mallory"))))
          case other                          => other
        }
        val expr = opExpr(SmtVerifyOp, StrValue(hex0x(root.value.value)), jsonToJlv(corrupted.asJson))
        evalExpr(expr).map {
          case Right(MapValue(m)) => expect(m.get("valid").contains(BoolValue(false)))
          case other              => failure(s"expected a valid:false result map, got $other")
        }
    }
  }

  test("smt_verify: malformed proof JSON is a Result error (not a crash, not a value)") {
    buildSmt.flatMap {
      case (root, _, _) =>
        // A bare object that is not a decodable SparseMerkleProof.
        val junk = MapValue(Map("nope" -> StrValue("not a proof")))
        val expr = opExpr(SmtVerifyOp, StrValue(hex0x(root.value.value)), junk)
        evalExpr(expr).map(r => expect(r.isLeft))
    }
  }

  test("smt_verify: malformed root hex is a Result error") {
    buildSmt.flatMap {
      case (_, incl, _) =>
        val expr = opExpr(SmtVerifyOp, StrValue("not-hex"), jsonToJlv(incl.asJson))
        evalExpr(expr).map(r => expect(r.isLeft))
    }
  }

  // ===========================================================================
  // worked example: allowlist / revocation gate
  // ===========================================================================

  test("worked example: {if [{smt_verify}.included] allowed denied} branches on present vs absent") {
    buildSmt.flatMap {
      case (root, incl, abs) =>
        def gate(proof: SparseMerkleProof): JsonLogicExpression =
          ApplyExpression(
            IfElseOp,
            List(
              ApplyExpression(
                GetOp,
                List(opExpr(SmtVerifyOp, StrValue(hex0x(root.value.value)), jsonToJlv(proof.asJson)), ConstExpression(StrValue("included")))
              ),
              ConstExpression(StrValue("allowed")),
              ConstExpression(StrValue("denied"))
            )
          )
        for {
          allowed <- evalExpr(gate(incl))
          denied  <- evalExpr(gate(abs))
        } yield expect(allowed == Right(StrValue("allowed"))) && expect(denied == Right(StrValue("denied")))
    }
  }

  // ===========================================================================
  // mpt_verify -- inclusion
  // ===========================================================================

  // An MPT keyed by short hex paths, with JSON string values.
  private val mptData: Map[Hex, String] =
    Map(Hex("a1") -> "v-a1", Hex("a2") -> "v-a2", Hex("b7") -> "v-b7")

  private def buildMpt: IO[MerklePatriciaTrie] =
    MerklePatriciaTrie.make[IO, String](mptData)

  test("mpt_verify: a real inclusion proof for key->value returns true") {
    buildMpt.flatMap { trie =>
      val rootHex = hex0x(trie.rootNode.digest.value)
      val key = Hex("a1")
      MerklePatriciaProver.make[IO](trie).attestPath(key).flatMap(IO.fromEither(_)).flatMap { proof =>
        val expr = opExpr(MptVerifyOp, StrValue(rootHex), StrValue(hex0x(key.value)), StrValue("v-a1"), jsonToJlv(proof.asJson))
        evalExpr(expr).map(r => expect(r == Right(BoolValue(true))))
      }
    }
  }

  test("mpt_verify: a wrong value returns false") {
    buildMpt.flatMap { trie =>
      val rootHex = hex0x(trie.rootNode.digest.value)
      val key = Hex("a1")
      MerklePatriciaProver.make[IO](trie).attestPath(key).flatMap(IO.fromEither(_)).flatMap { proof =>
        val expr = opExpr(MptVerifyOp, StrValue(rootHex), StrValue(hex0x(key.value)), StrValue("WRONG"), jsonToJlv(proof.asJson))
        evalExpr(expr).map(r => expect(r == Right(BoolValue(false))))
      }
    }
  }

  test("mpt_verify: a wrong root returns false") {
    buildMpt.flatMap { trie =>
      val key = Hex("a1")
      MerklePatriciaProver.make[IO](trie).attestPath(key).flatMap(IO.fromEither(_)).flatMap { proof =>
        val expr = opExpr(MptVerifyOp, StrValue(hex0x("ff" * 32)), StrValue(hex0x(key.value)), StrValue("v-a1"), jsonToJlv(proof.asJson))
        evalExpr(expr).map(r => expect(r == Right(BoolValue(false))))
      }
    }
  }

  test("mpt_verify: a wrong key (proof path mismatch) returns false") {
    buildMpt.flatMap { trie =>
      val rootHex = hex0x(trie.rootNode.digest.value)
      val key = Hex("a1")
      MerklePatriciaProver.make[IO](trie).attestPath(key).flatMap(IO.fromEither(_)).flatMap { proof =>
        // Query a different key than the proof attests.
        val expr = opExpr(MptVerifyOp, StrValue(rootHex), StrValue(hex0x("b7")), StrValue("v-a1"), jsonToJlv(proof.asJson))
        evalExpr(expr).map(r => expect(r == Right(BoolValue(false))))
      }
    }
  }

  test("mpt_verify: malformed proof JSON is a Result error") {
    buildMpt.flatMap { trie =>
      val rootHex = hex0x(trie.rootNode.digest.value)
      val junk = MapValue(Map("nope" -> StrValue("x")))
      val expr = opExpr(MptVerifyOp, StrValue(rootHex), StrValue(hex0x("a1")), StrValue("v-a1"), junk)
      evalExpr(expr).map(r => expect(r.isLeft))
    }
  }

  // ===========================================================================
  // mpt_prefix_verify -- authenticated, COMPLETE prefix proof
  // ===========================================================================

  // A trie whose keys share a prefix "ab", plus one outside it.
  private val prefixData: Map[Hex, String] =
    Map(Hex("ab12") -> "v1", Hex("ab34") -> "v2", Hex("ab56") -> "v3", Hex("cd99") -> "vx")

  private def buildPrefixTrie: IO[MerklePatriciaTrie] =
    MerklePatriciaTrie.make[IO, String](prefixData)

  /** The complete claimed entry-set under "ab" as a JLVM {keyHexRaw -> valueJson} object. */
  private def prefixEntries(pairs: (String, String)*): JsonLogicValue =
    MapValue(pairs.map { case (k, v) => k -> (StrValue(v): JsonLogicValue) }.toMap)

  test("mpt_prefix_verify: the COMPLETE entry set under a prefix verifies (true)") {
    buildPrefixTrie.flatMap { trie =>
      val rootHex = hex0x(trie.rootNode.digest.value)
      MerklePatriciaPrefixProver.make[IO](trie).attestPrefix(Hex("ab")).flatMap(IO.fromEither(_)).flatMap { proof =>
        val entries = prefixEntries("ab12" -> "v1", "ab34" -> "v2", "ab56" -> "v3")
        val expr = opExpr(MptPrefixVerifyOp, StrValue(rootHex), StrValue(hex0x("ab")), entries, jsonToJlv(proof.asJson))
        evalExpr(expr).map(r => expect(r == Right(BoolValue(true))))
      }
    }
  }

  test("mpt_prefix_verify: dropping an entry breaks completeness (false)") {
    buildPrefixTrie.flatMap { trie =>
      val rootHex = hex0x(trie.rootNode.digest.value)
      MerklePatriciaPrefixProver.make[IO](trie).attestPrefix(Hex("ab")).flatMap(IO.fromEither(_)).flatMap { proof =>
        // Missing ab56 -> the claimed key-set no longer equals the attested path-set.
        val entries = prefixEntries("ab12" -> "v1", "ab34" -> "v2")
        val expr = opExpr(MptPrefixVerifyOp, StrValue(rootHex), StrValue(hex0x("ab")), entries, jsonToJlv(proof.asJson))
        evalExpr(expr).map(r => expect(r == Right(BoolValue(false))))
      }
    }
  }

  test("mpt_prefix_verify: altering a claimed value breaks value-binding (false)") {
    buildPrefixTrie.flatMap { trie =>
      val rootHex = hex0x(trie.rootNode.digest.value)
      MerklePatriciaPrefixProver.make[IO](trie).attestPrefix(Hex("ab")).flatMap(IO.fromEither(_)).flatMap { proof =>
        val entries = prefixEntries("ab12" -> "v1", "ab34" -> "WRONG", "ab56" -> "v3")
        val expr = opExpr(MptPrefixVerifyOp, StrValue(rootHex), StrValue(hex0x("ab")), entries, jsonToJlv(proof.asJson))
        evalExpr(expr).map(r => expect(r == Right(BoolValue(false))))
      }
    }
  }

  test("mpt_prefix_verify: adding an extra (out-of-set) entry breaks completeness (false)") {
    buildPrefixTrie.flatMap { trie =>
      val rootHex = hex0x(trie.rootNode.digest.value)
      MerklePatriciaPrefixProver.make[IO](trie).attestPrefix(Hex("ab")).flatMap(IO.fromEither(_)).flatMap { proof =>
        val entries = prefixEntries("ab12" -> "v1", "ab34" -> "v2", "ab56" -> "v3", "abff" -> "ghost")
        val expr = opExpr(MptPrefixVerifyOp, StrValue(rootHex), StrValue(hex0x("ab")), entries, jsonToJlv(proof.asJson))
        evalExpr(expr).map(r => expect(r == Right(BoolValue(false))))
      }
    }
  }

  test("mpt_prefix_verify: SUBSET-OMISSION -- a genuine batch proof for a strict subset is INCOMPLETE (false)") {
    // SOUNDNESS: there are >=3 keys under prefix "ab"; the prover attests only {ab12, ab34} with a
    // GENUINE batch inclusion proof. The shared branch under the prefix still commits child '5'
    // (ab56), so the completeness traversal finds an unattested leaf under the prefix.
    buildPrefixTrie.flatMap { trie =>
      val rootHex = hex0x(trie.rootNode.digest.value)
      MerklePatriciaBatchInclusionProver
        .make[IO](trie)
        .attestPaths(List(Hex("ab12"), Hex("ab34")))
        .flatMap(IO.fromEither(_))
        .flatMap { proof =>
          // The claimed key-set EQUALS the attested path-set (the prover's own lists agree), batch
          // inclusion passes, values bind -- only the completeness traversal can reject this.
          val entries = prefixEntries("ab12" -> "v1", "ab34" -> "v2")
          val expr = opExpr(MptPrefixVerifyOp, StrValue(rootHex), StrValue(hex0x("ab")), entries, jsonToJlv(proof.asJson))
          evalExpr(expr).map(r => expect(r == Right(BoolValue(false))))
        }
    }
  }

  test("mpt_prefix_verify: SWAPPED-PER-KEY -- swapping which value belongs to which key fails (false)") {
    // SOUNDNESS: the COMPLETE, fully-attested set under prefix "ab", but ab12 and ab34's values are
    // swapped. A set-membership value check would pass (both v1 and v2 digests are among the leaves);
    // per-key binding requires the leaf reached by ab12's path to commit v1, not v2.
    buildPrefixTrie.flatMap { trie =>
      val rootHex = hex0x(trie.rootNode.digest.value)
      MerklePatriciaPrefixProver.make[IO](trie).attestPrefix(Hex("ab")).flatMap(IO.fromEither(_)).flatMap { proof =>
        val entries = prefixEntries("ab12" -> "v2", "ab34" -> "v1", "ab56" -> "v3")
        val expr = opExpr(MptPrefixVerifyOp, StrValue(rootHex), StrValue(hex0x("ab")), entries, jsonToJlv(proof.asJson))
        evalExpr(expr).map(r => expect(r == Right(BoolValue(false))))
      }
    }
  }

  test("mpt_prefix_verify: malformed batch-proof JSON is a Result error") {
    buildPrefixTrie.flatMap { trie =>
      val rootHex = hex0x(trie.rootNode.digest.value)
      val entries = prefixEntries("ab12" -> "v1")
      val junk = MapValue(Map("nope" -> StrValue("x")))
      val expr = opExpr(MptPrefixVerifyOp, StrValue(rootHex), StrValue(hex0x("ab")), entries, junk)
      evalExpr(expr).map(r => expect(r.isLeft))
    }
  }
}
